### ISSUE TITLE
Unnecessary use of Mutex

### ISSUE THREAD

**Issue by ioquatix** [DSG-UniFE/ruby-mhl#1]
It's 2AM, this might not be the issue, but lets start the discussion here.

https://github.com/mtortonesi/ruby-mhl/blob/03a807af29717e7dbc684a94f7e3e784e9c7d442/lib/mhl/genetic_algorithm_solver.rb#L135-L148

I don't think this mutex is necessary. I looked at the history of the code and it was from before you used `Concurrent::Promise`. Because you have a single mutex for all your promises, you essentially fan out N threads only to serialise the final step in your process.

Finally, I tested the performance of this code, and this was some weeks (months?) ago, I actually found the performance was *worse* with threads than without. I have a branch on my laptop that I was playing around with and it's not in front of me, but maybe it's good for you to test it yourself.  I think your specs had some basic performance tests (or something you could wrap a timer around).

**Comment by mtortonesi** [comment]
Sorry for the super late reply. Good catch with the unnecessary Mutex! Thanks! I just got rid of it in [Commit 680d031](https://github.com/mtortonesi/ruby-mhl/commit/680d03197819b19c6e818ac70766bfd17e953159).

WRT the performance comment, you are right of course. With computationally light target functions, the multithreaded approach might perform worse than the single threaded one. But I created ruby-mhl specifically to consider computationally heavy and parallelizable target functions, such as [sisfc](https://github.com/mtortonesi/sisfc) simulations. In this use case, leveraging multiple threads and GIL-less JRuby seemed to be the proper way to go. (Now that TruffleRuby seems to be quite mature, I am planning to give it a try, though.)
